"""Contract-first manager API for compiled UniLab tasks."""

from .backend_resolver import BackendEntityResolver
from .compiler import TaskCompiler
from .entities import (
    CompiledSelector,
    EntityKind,
    EntityResolver,
    EntitySelector,
    ManagerContractError,
    SelectorMode,
)
from .fingerprint import (
    MANAGED_POLICY_ABI_SNAPSHOT_VERSION,
    ManagedPolicyABISnapshotError,
    managed_policy_abi_snapshot,
    normalize_managed_policy_abi_snapshot,
)
from .plan import (
    MANAGER_TASK_CONTRACT_VERSION,
    CompiledTaskPlan,
    CompiledTerm,
    ObservationGroupPlan,
    ObservationOutput,
    OutputChannelPlan,
    OutputSlice,
    PolicyABI,
)
from .registry import TermRegistry
from .runtime import (
    ManagedKernelBinding,
    ManagedLifecycleEvent,
    ManagedLifecyclePhase,
    ManagedMetric,
    ManagedReferenceRuntime,
    ManagedResetRequest,
    ManagedRuntimeBuffer,
    ManagedRuntimeBufferAddress,
    ManagedRuntimeBufferProvider,
    ManagedRuntimeError,
    ManagedRuntimeStabilityDiagnostics,
    ManagedTaskKernel,
)
from .spec import (
    FrozenParameters,
    MutationTemplate,
    NormalizationMode,
    ParameterKind,
    ParameterSpec,
    PolicySpec,
    QuaternionOrder,
    StateRequirement,
    TaskSpec,
    TensorSpec,
    TermDefinition,
    TermInvocation,
    TermPhase,
    TermRole,
    freeze_parameters,
)

__all__ = [
    "MANAGER_TASK_CONTRACT_VERSION",
    "BackendEntityResolver",
    "CompiledSelector",
    "CompiledTaskPlan",
    "CompiledTerm",
    "EntityKind",
    "EntityResolver",
    "EntitySelector",
    "FrozenParameters",
    "ManagerContractError",
    "ManagedPolicyABISnapshotError",
    "ManagedLifecycleEvent",
    "ManagedLifecyclePhase",
    "ManagedKernelBinding",
    "ManagedMetric",
    "ManagedReferenceRuntime",
    "ManagedResetRequest",
    "ManagedRuntimeBuffer",
    "ManagedRuntimeBufferAddress",
    "ManagedRuntimeBufferProvider",
    "ManagedRuntimeError",
    "ManagedRuntimeStabilityDiagnostics",
    "ManagedTaskKernel",
    "MutationTemplate",
    "NormalizationMode",
    "MANAGED_POLICY_ABI_SNAPSHOT_VERSION",
    "ObservationGroupPlan",
    "ObservationOutput",
    "OutputChannelPlan",
    "OutputSlice",
    "ParameterKind",
    "ParameterSpec",
    "PolicyABI",
    "PolicySpec",
    "QuaternionOrder",
    "SelectorMode",
    "StateRequirement",
    "TaskCompiler",
    "TaskSpec",
    "TensorSpec",
    "TermDefinition",
    "TermInvocation",
    "TermPhase",
    "TermRegistry",
    "TermRole",
    "freeze_parameters",
    "managed_policy_abi_snapshot",
    "normalize_managed_policy_abi_snapshot",
]
