"""Shared training helpers for entrypoint scripts."""

from unilab.training.backend_adapter import BackendAdapter
from unilab.training.common import (
    assert_offpolicy_task_choice_matches_algo,
    create_env,
    ensure_registries,
    get_hydra_runtime_choice,
    setup_logger,
)
from unilab.training.entrypoints import (
    ENTRYPOINT_CONTRACT_FINGERPRINT,
    EntrypointContractError,
    EntrypointDisposition,
    EntrypointRoute,
    EntrypointRouteContract,
    PolicyLoadTarget,
    build_entrypoint_receipt,
    guarded_policy_load,
    policy_load_target,
    preflight_policy_source,
    require_entrypoint_route,
    require_policy_load_contracts,
    resolve_entrypoint_contract,
    resolve_ppo_operation,
)
from unilab.training.experiment import ExperimentTracker
from unilab.training.monitoring import HardwareMonitor
from unilab.training.run import (
    get_entrypoint_log_root,
    get_latest_checkpoint,
    get_latest_run,
    get_log_root,
    log_playback_plan,
    parse_checkpoint_path,
    resolve_checkpoint_path,
    resolve_task_checkpoint_path,
    should_run_playback,
)
from unilab.training.seed import (
    TrainingSeedInfo,
    apply_configured_training_seed,
    apply_training_seed,
    derive_worker_seed,
    resolve_training_seed,
)

__all__ = [
    "BackendAdapter",
    "ENTRYPOINT_CONTRACT_FINGERPRINT",
    "EntrypointContractError",
    "EntrypointDisposition",
    "EntrypointRoute",
    "EntrypointRouteContract",
    "ExperimentTracker",
    "HardwareMonitor",
    "PolicyLoadTarget",
    "assert_offpolicy_task_choice_matches_algo",
    "create_env",
    "build_entrypoint_receipt",
    "ensure_registries",
    "get_entrypoint_log_root",
    "get_hydra_runtime_choice",
    "get_latest_checkpoint",
    "get_latest_run",
    "get_log_root",
    "guarded_policy_load",
    "log_playback_plan",
    "parse_checkpoint_path",
    "policy_load_target",
    "preflight_policy_source",
    "require_entrypoint_route",
    "require_policy_load_contracts",
    "resolve_checkpoint_path",
    "resolve_entrypoint_contract",
    "resolve_ppo_operation",
    "resolve_task_checkpoint_path",
    "should_run_playback",
    "TrainingSeedInfo",
    "apply_configured_training_seed",
    "apply_training_seed",
    "derive_worker_seed",
    "resolve_training_seed",
    "setup_logger",
]
